# -*- coding: utf-8 -*-
"""Kmeansclusterring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zQ2KxMXpADc8tLGn1wo3tsV_4WjQPXC3
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
# %matplotlib inline

#generate random data
X= -2 * np.random.rand(100,2)
X1 = 1 + 2 * np.random.rand(50,2)
X[50:100, :] = X1
plt.scatter(X[ : , 0], X [: , 1], s =50,c = 'b')
plt.show()

from sklearn.cluster import KMeans
Kmean = KMeans(n_clusters = 2)
Kmean.fit(X)

#finding the centroid
Kmean.cluster_centers_

#displaying cluster centroids using red and green)
plt.scatter(X[: , 0] , X[: , 1] , s = 50 , c = 'b')
plt.scatter( 1.81562075 ,1.96166628 , s= 200 , c ='g' , marker = 's')
plt.scatter(-1.07387577 , -0.99789019 , s =200 , c ='r' , marker = 's')
plt.show()

#testing the algorithm
Kmean.labels_

sample_test = np.array([-3.0  , -3.0])
second_test = sample_test.reshape(1,-1)
Kmean.predict(second_test)